use FinalProject;
update Treasure set category= "Coin" where treasure_id = 2231;
update Treasure set category= "Coin" where treasure_id = 2275;
update Treasure set category= "Coin" where treasure_id = 2279;
update Treasure set category= "Coin" where treasure_id = 2293;
update Treasure set category= "Coin" where treasure_id = 2303;
update Treasure set category= "Coin" where treasure_id = 2305;
update Treasure set category= "Buddha Statues" where treasure_id = 2214;
update Treasure set category= "Buddha Statues" where treasure_id = 2216;
update Treasure set category= "Buddha Statues" where treasure_id = 2224;
update Treasure set category= "Buddha Statues" where treasure_id = 2229;
update Treasure set category= "Buddha Statues" where treasure_id = 2313;
update Treasure set category= "Carving" where treasure_id = 2123;
update Treasure set category= "Carving" where treasure_id = 2124;
update Treasure set category= "Carving" where treasure_id = 2125;
update Treasure set category = "Bronze" where treasure_id = 2080;
update Treasure set img = null where treasure_id = 2080;
update Treasure set category = "Bronze" where treasure_id = 2083;
update Treasure set img = null where treasure_id = 2083;
update Treasure set category = "Bronze" where treasure_id = 2084;
update Treasure set img = null where treasure_id = 2084;
update Treasure set category = "Bronze" where treasure_id = 2096;
update Treasure set img = null where treasure_id = 2096;
update Treasure set category = "Bronze" where treasure_id = 2097;
update Treasure set img = null where treasure_id = 2097;
update Treasure set category = "Bronze" where treasure_id = 2104;
update Treasure set img = null where treasure_id = 2104;
update Treasure set category = "Bronze" where treasure_id = 2122;
update Treasure set img = null where treasure_id = 2122;
update Treasure set category = "Bronze" where treasure_id = 2128;
update Treasure set img = null where treasure_id = 2128;

update Treasure set category = "Ceramic" where treasure_id = 2093;
update Ttreasure set img = null where treasure_id = 2093;
update Treasure set category = "Ceramic" where treasure_id = 2108;
update Treasure set img = null where treasure_id = 2108;
update Treasure set category = "Ceramic" where treasure_id = 2111;
update Treasure set img = null where treasure_id = 2111;
update Treasure set category = "Ceramic" where treasure_id = 2120;
update Treasure set img = null where treasure_id = 2120;
update Treasure set category = "Ceramic" where treasure_id = 2129;
update Treasure set img = null where treasure_id = 2129;
update Treasure set category = "Ceramic" where treasure_id = 2133;
update Treasure set img = null where treasure_id = 2133;
update Treasure set category = "Ceramic" where treasure_id = 2134;
update Treasure set img = null where treasure_id = 2134;
update Treasure set category = "Ceramic" where treasure_id = 2136;
update Treasure set img = null where treasure_id = 2136;
update Treasure set category = "Others" where treasure_id = 2106;
update Treasure set img = null where treasure_id = 2106;
update Treasure set category = "Others" where treasure_id = 2126;
update Treasure set img = null where treasure_id = 2126;
update Treasure set category = "Others" where treasure_id = 2127;
update Treasure set img = null where treasure_id = 2127;

update Treasure set category = "Jade" where treasure_id = 2115;
update Treasure set img = null where treasure_id = 2115;

update Treasure set category= "Painting" where treasure_id = 2220;
update Treasure set category= "Painting" where treasure_id = 2225;
update Treasure set category= "Painting" where treasure_id = 2228;
update Treasure set category= "Jade" where treasure_id = 2222;
update Treasure set category= "Lacquer" where treasure_id = 2226;
update Treasure set category= "Jade" where treasure_id = 2233;
update Treasure set category= "Jade" where treasure_id = 2248;
update Treasure set category= "Jade" where treasure_id = 2255;
update Treasure set category= "Lacquer" where treasure_id = 2243;
update Treasure set category= "Lacquer" where treasure_id = 2245;
update Treasure set category= "Calligraphy" where treasure_id = 2257;
update Treasure set category= "Bronze" where treasure_id = 2258;
update Treasure set category= "Bronze" where treasure_id = 2264;
update Treasure set category= "Bronze" where treasure_id = 2290;
update Treasure set category= "Bronze" where treasure_id = 2291;
update Treasure set category= "Bronze" where treasure_id = 2294;
update Treasure set category= "Bronze" where treasure_id = 2299;
update Treasure set category= "Jade" where treasure_id = 2259;
update Treasure set category= "Jade" where treasure_id = 2287;
update Treasure set category= "Jade" where treasure_id = 2308;
update Treasure set category= "Lacquer" where treasure_id = 2260;
update Treasure set category= "Lacquer" where treasure_id = 2261;
update Treasure set category= "Lacquer" where treasure_id = 2273;
update Treasure set category= "Lacquer" where treasure_id = 2300;
update Treasure set category= "Calligraphy" where treasure_id = 2276;
update Treasure set category= "Calligraphy" where treasure_id = 2277;
update Treasure set category= "Calligraphy" where treasure_id = 2309;
update Treasure set category= "Calligraphy" where treasure_id = 2310;
update Treasure set category= "Calligraphy" where treasure_id = 2311;
update Treasure set category = "Others" where treasure_id = 2337;
update Treasure set category = "Others" where treasure_id = 2338;
update Treasure set category = "Others" where treasure_id = 2343;
update Treasure set category = "Others" where treasure_id = 2344;
update Treasure set category = "Others" where treasure_id = 2345;
update Treasure set category = "Others" where treasure_id = 2352;
update Treasure set category = "Others" where treasure_id = 2357;
update Treasure set category = "Others" where treasure_id = 2360;
update Treasure set category = "Others" where treasure_id = 2363;
update Treasure set category = "Others" where treasure_id = 2364;
update Treasure set category = "Others" where treasure_id = 2367;
update Treasure set category = "Others" where treasure_id = 2371;
update Treasure set category = "Others" where treasure_id = 2372;
update Treasure set category = "Others" where treasure_id = 2375;
update Treasure set category = "Others" where treasure_id = 2377;
update Treasure set category = "Others" where treasure_id = 2384;
update Treasure set category = "Others" where treasure_id = 2385;
update Treasure set category = "Others" where treasure_id = 2392;
update Treasure set category = "Others" where treasure_id = 2403;
update Treasure set category = "Others" where treasure_id = 2411;
update Treasure set category = "Others" where treasure_id = 2412;
update Treasure set category = "Others" where treasure_id = 2421;
update Treasure set category = "Others" where treasure_id = 2426;
update Treasure set category = "Others" where treasure_id = 2430;